async function main() {
    // to do
}

main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
});
